image: maven:3-openjdk-8

deploy:
  stage: deploy
  script: mvn clean install
    -Dmaven.test.skip
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

cache:
  paths:
    - .m2
    - frontend/node
    - frontend/node_modules
