image: maven:3-openjdk-8

deploy:
  stage: deploy
  script:
    - git clone
        --single-branch --branch m2
        https://gitlab-ci:$DEPLOY_TOKEN@gitlab.switch.ch/cast/annotate.git
        m2
    - mvn clean deploy
        -Dmaven.test.skip
        -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
        -DaltDeploymentRepository=m2::default::file:m2
    - cd m2
    - git add .
    - git commit -m 'Update m2'
    - git push

  except:
    branches:
      - m2

cache:
  paths:
    - .m2
    - frontend/node
    - frontend/node_modules
